# Generated by Django 3.2.16 on 2022-11-25 11:55

import aesfield.field
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210511_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='secret',
            field=aesfield.field.AESField(
                aes_key='api_key:secret',
                aes_method=getattr(settings, 'AES_METHOD', 'aesfield.default'),
                aes_prefix='aes:',
                max_length=100000,
            ),
        ),
        migrations.AddConstraint(
            model_name='apikey',
            constraint=models.CheckConstraint(
                check=models.Q(('secret__length__lte', 100000)),
                name='api_apikey_secret_3a33d90a_mlen',
            ),
        ),
    ]
