# Generated by Django 3.2.16 on 2022-11-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='localized_string',
            field=models.TextField(max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='translation',
            name='localized_string_clean',
            field=models.TextField(max_length=100000, null=True),
        ),
        migrations.AddConstraint(
            model_name='translation',
            constraint=models.CheckConstraint(check=models.Q(('localized_string__length__lte', 100000)), name='translation_localiz_db2f24a5_mlen'),
        ),
        migrations.AddConstraint(
            model_name='translation',
            constraint=models.CheckConstraint(check=models.Q(('localized_string_clean__length__lte', 100000)), name='translation_localiz_61ea83e1_mlen'),
        ),
    ]
