# Generated by Django 3.2.16 on 2022-11-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocklist', '0027_auto_20220530_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='reason',
            field=models.TextField(blank=True, max_length=100000),
        ),
        migrations.AlterField(
            model_name='blocklistsubmission',
            name='input_guids',
            field=models.TextField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='blocklistsubmission',
            name='reason',
            field=models.TextField(blank=True, help_text='Note this reason will be displayed publicly on the block-addon pages.', max_length=100000),
        ),
        migrations.AddConstraint(
            model_name='blocklistsubmission',
            constraint=models.CheckConstraint(check=models.Q(('input_guids__length__lte', 100000)), name='blocklist_b_input_g_d441c98b_mlen'),
        ),
        migrations.AddConstraint(
            model_name='blocklistsubmission',
            constraint=models.CheckConstraint(check=models.Q(('reason__length__lte', 100000)), name='blocklist_b_reason_e90c448a_mlen'),
        ),
    ]
