CREATE TABLE `webapps_georestrictions` (
    `id` int(11) unsigned AUTO_INCREMENT NOT NULL PRIMARY KEY,
    `created` datetime NOT NULL,
    `modified` datetime NOT NULL,
    `addon_id` int(11) unsigned NOT NULL UNIQUE,
    `use_strict` bool NOT NULL,
    `enable_new_regions` bool NOT NULL,
    `region_br` bool NOT NULL,
    `region_co` bool NOT NULL,
    `region_de` bool NOT NULL,
    `region_es` bool NOT NULL,
    `region_gr` bool NOT NULL,
    `region_hu` bool NOT NULL,
    `region_me` bool NOT NULL,
    `region_mx` bool NOT NULL,
    `region_pl` bool NOT NULL,
    `region_rs` bool NOT NULL,
    `region_uk` bool NOT NULL,
    `region_us` bool NOT NULL,
    `region_ve` bool NOT NULL,
    `region_worldwide` bool NOT NULL,
    `carrier_america_movil` bool NOT NULL,
    `carrier_carrierless` bool NOT NULL,
    `carrier_china_unicom` bool NOT NULL,
    `carrier_deutsche_telekom` bool NOT NULL,
    `carrier_etisalat` bool NOT NULL,
    `carrier_hutchinson_three_group` bool NOT NULL,
    `carrier_kddi` bool NOT NULL,
    `carrier_kt` bool NOT NULL,
    `carrier_megafon` bool NOT NULL,
    `carrier_qtel` bool NOT NULL,
    `carrier_singtel` bool NOT NULL,
    `carrier_smart` bool NOT NULL,
    `carrier_sprint` bool NOT NULL,
    `carrier_telecom_italia_group` bool NOT NULL,
    `carrier_telefonica` bool NOT NULL,
    `carrier_telenor` bool NOT NULL,
    `carrier_tmn` bool NOT NULL,
    `carrier_vimpelcom` bool NOT NULL
) ENGINE=InnoDB CHARACTER SET utf8 COLLATE utf8_general_ci;

ALTER TABLE `webapps_georestrictions` ADD CONSTRAINT `addon_id_key`
FOREIGN KEY (`addon_id`) REFERENCES `addons` (`id`) ON DELETE CASCADE;
