# Generated by Django 3.2.16 on 2022-11-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewers', '0020_auto_20221114_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cannedresponse',
            name='response',
            field=models.TextField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='reviewactionreason',
            name='canned_response',
            field=models.TextField(max_length=100000),
        ),
        migrations.AddConstraint(
            model_name='cannedresponse',
            constraint=models.CheckConstraint(check=models.Q(('response__length__lte', 100000)), name='reviewers_c_respons_5478cf46_mlen'),
        ),
        migrations.AddConstraint(
            model_name='reviewactionreason',
            constraint=models.CheckConstraint(check=models.Q(('canned_response__length__lte', 100000)), name='reviewers_r_canned__1620c122_mlen'),
        ),
        migrations.AddConstraint(
            model_name='whiteboard',
            constraint=models.CheckConstraint(check=models.Q(('private__length__lte', 100000)), name='reviewers_w_private_f61f693c_mlen'),
        ),
        migrations.AddConstraint(
            model_name='whiteboard',
            constraint=models.CheckConstraint(check=models.Q(('public__length__lte', 100000)), name='reviewers_w_public_cecfb310_mlen'),
        ),
    ]
