# Generated by Django 3.2.16 on 2022-11-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0013_homepageshelves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discoveryitem',
            name='custom_description',
            field=models.TextField(blank=True, help_text='Longer text used to describe an add-on. Should not contain any HTML or special tags. Will be translated.', max_length=100000),
        ),
    ]
