# Generated by Django 3.2.16 on 2022-11-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_userprofile_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='notes',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.CheckConstraint(check=models.Q(('notes__length__lte', 100000)), name='users_userp_notes_eefe52f7_mlen'),
        ),
    ]
