# Generated by Django 3.2.16 on 2022-11-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_give_api_bypass_throttling_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='notes',
            field=models.TextField(blank=True, max_length=100000),
        ),
        migrations.AlterField(
            model_name='group',
            name='rules',
            field=models.TextField(max_length=100000),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.CheckConstraint(check=models.Q(('rules__length__lte', 100000)), name='access_grou_rules_26288a03_mlen'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.CheckConstraint(check=models.Q(('notes__length__lte', 100000)), name='access_grou_notes_8a8e0423_mlen'),
        ),
    ]
