# Generated by Django 3.2.16 on 2022-11-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakeemail',
            name='message',
            field=models.TextField(max_length=100000),
        ),
        migrations.AddConstraint(
            model_name='fakeemail',
            constraint=models.CheckConstraint(check=models.Q(('message__length__lte', 100000)), name='amo_fakeema_message_f2115d0e_mlen'),
        ),
    ]
