# Generated by Django 3.2.16 on 2022-11-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0030_auto_20221122_1312'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='version',
            constraint=models.CheckConstraint(check=models.Q(('approval_notes__length__lte', 100000)), name='versions_ve_approva_efd2e2d3_mlen'),
        ),
    ]
