# Generated by Django 2.2.6 on 2019-10-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0002_addon_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='addonreviewerflags',
            name='needs_human_review',
            field=models.NullBooleanField(default=None),
        ),
    ]
