# Generated by Django 3.2.16 on 2022-11-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0041_auto_20221122_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deniedguid',
            name='comments',
            field=models.TextField(blank=True, default='', max_length=100000),
        ),
        migrations.AddConstraint(
            model_name='deniedguid',
            constraint=models.CheckConstraint(check=models.Q(('comments__length__lte', 100000)), name='addons_deni_comment_23b0904c_mlen'),
        ),
    ]
