# Generated by Django 3.2.16 on 2022-11-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0007_auto_20220803_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abusereport',
            name='message',
            field=models.TextField(blank=True, max_length=100000),
        ),
        migrations.AddConstraint(
            model_name='abusereport',
            constraint=models.CheckConstraint(check=models.Q(('message__length__lte', 100000)), name='abuse_abuse_message_b1d0373b_mlen'),
        ),
    ]
